### ISSUE TITLE
Feature Request: A list of tabs that have made a sound...

### ISSUE THREAD

**Issue by sasconsul** [jaredsohn/mutetab#13]
I have been having trouble finding which tab has sent a notification of started playing.  I was wondering if a list of the N most recent tabs generating sounds could be kept?

Alos, there have been some tabs that start without be asked that suddenly start playing.  I want to track down those tabs so i can avoid those sites or blacklist them.

Stuart

**Comment by jaredsohn** [comment]
It does this; it shows tabs that recently made a sound at the top.

I use this myself a lot when I hear a random noise and I don't know which tab it was. There is a `Recently noisy or playing tabs` section that will show toward the top.
