### ISSUE TITLE
Unmuted tab gets muted again when pulled off tab bar

### ISSUE THREAD

**Issue by vajrang** [jaredsohn/mutetab#2]
MuteTab Default Muting Behavior: Background tab muted.

1. Unmute tab, play some video
2. Tear off the playing tab from Chrome tab into separate window
3. Tab gets muted again.

Expected behavior: Once unmuted, a tab shouldn't be muted again by the extension.

**Comment by jaredsohn** [comment]
Thanks for posting an issue.

Fixed in v3.0.3.
