### ISSUE TITLE
Mute new tab

### ISSUE THREAD

**Issue by dmartinp** [jaredsohn/mutetab#5]
Currently I have mute all tabs selected in options. However, when creating a new tab, it is unmuted.

**Comment by jaredsohn** [comment]
I just tried this and it worked okay for me.

Can you verify that 'mute by default' is set within settings by reopening the options page?

What steps do you take to create a new tab? (cmd-t? clicking on the button on the right side of the tab list?

Which version of Chrome are you running? (I am testing on Chrome 63.0.3239.132 (Official Build) (64-bit).)

**Comment by dmartinp** [comment]
Ok I restored to default settings and then rechecked the mute by default setting and seems to be working!! Great extension, Thanks!
