### ISSUE TITLE
Facebook auto unmutes tab

### ISSUE THREAD

**Issue by dmartinp** [jaredsohn/mutetab#6]
Hello, I am on Chrome Version 63.0.3239.132 (Official Build) (64-bit) on Mac OS X 10.13.2 and I've noticed only recently that when opening an automuted new tab and going to Facebook, Facebook auto unmutes the tab. Anyone else notice this behavior? Is this a new setting within Facebook?

**Comment by jaredsohn** [comment]
@dmartinp I don't think Facebook has the ability to affect muting done by Chrome. It certainly wasn't possible when browser tab muting was created; you probably discovered a bug in MuteTab. It is also possible (but unlikely, I think) that you are running another extension that unmutes the tab when you visit it.

**Comment by dmartinp** [comment]
Ah I see, by default (which I don't know why) facebook is added to the whitelist
